FROM maven:3.8.7-eclipse-temurin-19-alpine AS build

WORKDIR /app

COPY pom.xml ./
RUN mvn dependency:go-offline

COPY src ./src

RUN mvn clean package -DskipTests

FROM eclipse-temurin:19-alpine

WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

ENV MAIL_USERNAME=${MAIL_USERNAME}
ENV MAIL_PASSWORD=${MAIL_PASSWORD}
ENV TOKENS_PATH=${TOKENS_PATH}
ENV SPREADSHEET_ID=${SPREADSHEET_ID}

ENV GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
ENV GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
ENV GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}
ENV GOOGLE_AUTH_URI=${GOOGLE_AUTH_URI}
ENV GOOGLE_TOKEN_URI=${GOOGLE_TOKEN_URI}
ENV GOOGLE_CERT_URL=${GOOGLE_CERT_URL}
ENV GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]